add opts to authorize so that pre_hooks can build more complex subjects/objects
woylie/let_me pull request #38
Opened 2023-05-26 22:47 UTC by hogiyogi597

# **Description**

I'd like to encourage a separation of the `object` from other, potentially influential args that could be set dynamically. For example, in the context of a credit card application I may want to freeze a card and as part of that request I have the `card` to be frozen and the `frozen_reason` I'd like to set it to. It is reasonable to assume there are certain `frozen_reason`s that I would want to prevent users from using since they could be system level reasons.

Currently, `pre_hook`s only allow static values to be passed as options which is useful but I'd like to expand on that idea and allow callers of `authorize` to pass arguments that can be dynamically set through requests so it would be something like:

```elixir

def freeze_card(user, card, reason) do
  ...
  CardPolicy.authorize?(:card_freeze, user, card, reason)
  ...
end

# Policy
...
object :card do
  ...
  action :freeze do
    pre_hook :load_reason
    allow [:owns_card, :valid_reason]
  end
  ...
end

# Checks
def owns_card(%{id: id}, %{card: %{user_id: id}}), do: true
def owns_card(_, _), do: false

def valid_reason(_, %{reason: :frozen_by_user), do: true
def valid_reason(_, _), do: false

# Pre_hooks
def load_reason(user, card, reason), do: {user, %{card: card, reason: reason}}

```

# **Checklist**

- [x] I added tests that cover my proposed changes.
- [x] I updated the documentation related to my changes (if applicable).

2023-05-27 00:57 UTC, woylie requested changes
Thanks, this looks useful, just a few comments. Also, there are some warnings now about invalid references in the docs, can you fix them?

Do you think it would make sense to pass those options to the check functions as well?

2023-05-27 00:57 UTC, woylie commented on lib/let_me/policy.ex
> +      MyApp.Policy.authorize!(:article_view, %{age: 10}, 50)
The object argument is missing here, and the last argument needs to be an enumerable.

2023-05-27 00:57 UTC, woylie commented on test/support/hooks.ex
> +    factor = Keyword.get(opts, :factor)
```suggestion
    factor = Keyword.fetch!(opts, :factor)
```

2023-05-27 00:57 UTC, woylie commented on lib/let_me/policy.ex
> +  @callback authorize(atom, any, any, any) :: :ok | {:error, any}
With your changes of the `build_pre_hook_calls` macro, the fourth argument is expected to be an `Enumerable.t()`. But I also think we can save us the `Enum.into` and enforce a `keyword`.

2023-05-30 16:47 UTC, hogiyogi597 commented
Thanks for your comments! I'll fix up the branch with your suggestions. 

Also, I appreciate you working with me through contributions. I hope you don't feel like I am infringing on your project! If you do, just let me (lol) know. I want to be respectful of your work. I have really enjoyed working on our LetMe implementation.

> Do you think it would make sense to pass those options to the check functions as well?

I originally thought that it might make sense to pass into the check functions but I could go either way honestly. I kinda like how simple the check functions interface is currently. That's why I initially opted to just allow pre hooks to build up the subject/object. But I am open to ideas; what would be your preference?

2023-06-11 01:16 UTC, woylie commented on CHANGELOG.md
> +- Renamed `c:LetMe.Policy.authorized?/3` to `c:LetMe.Policy.authorize?/4`,
```suggestion
- Renamed `c:LetMe.Policy.authorized?/3` to `c:LetMe.Policy.authorize?/3`,
```

2023-06-11 01:29 UTC, woylie commented on lib/let_me/policy.ex
> +  @callback authorize(atom, any, any, Keyword.t()) :: :ok | {:error, any}
```suggestion
  @callback authorize(atom, any, any, keyword) :: :ok | {:error, any}
```

2023-06-11 01:29 UTC, woylie commented on lib/let_me/policy.ex
> +  @callback authorize!(atom, any, any, any) :: :ok
```suggestion
  @callback authorize!(atom, any, any, keyword) :: :ok
```

2023-06-11 01:29 UTC, woylie commented on lib/let_me/policy.ex
> +  @callback authorize?(atom, any, any, any) :: boolean
```suggestion
  @callback authorize?(atom, any, any, keyword) :: boolean
```

2023-06-11 01:35 UTC, woylie approved these changes

2023-06-11 01:35 UTC, merged

2023-06-11 01:36 UTC, woylie commented
That should do, thanks!