Add automatic typespecs for `authorize` functions
woylie/let_me pull request #41
Opened 2023-06-23 00:41 UTC by bernardd

**Description**

This change adds auto-generation of an @action typespec and @specs for the various `authorize` calls in a generated policy module. These typespecs explicitly specify the supported actions, allowing dialyzer to be used for static checking of the validity of action names passed in.

**Checklist**

- [x] I added tests that cover my proposed changes.
- [x] I updated the documentation related to my changes (if applicable).

2023-06-23 00:45 UTC, bernardd commented
Not sure what that dialyzer failure is about, but someone was talking over on the Elixir Slack about the same issue suddenly appearing on a different project so I suspect it's not down to this change :)

2023-06-23 00:48 UTC, woylie commented
Great, thanks for the PR! I'll have closer look later.

I don't know where the dialyzer error is coming from, but deleting the PLT caches resolved it in other projects.

2023-06-23 05:55 UTC, woylie commented on lib/let_me/builder.ex
> +      @type actions() :: unquote(typespec)
I think this should be singular.

```suggestion
      @type action() :: unquote(typespec)
```

2023-06-23 05:55 UTC, woylie commented on lib/let_me/builder.ex
> +      @spec authorize?(actions, any, any, keyword) :: boolean()
```suggestion
      @spec authorize?(action(), any, any, keyword) :: boolean()
```

2023-06-23 05:56 UTC, woylie commented on lib/let_me/builder.ex
> +      @type actions() :: unquote(typespec)
Can we add a `@typedoc` here?

2023-06-23 06:04 UTC, woylie commented
I just tried your branch in a project and changed an action in an `authorize/3` call to an invalid action, but Dialyzer didn't complain. My guess is that it doesn't work like this because the policy module implements the `LetMe.Policy` behaviour, and it is not possible to override the type specifications of the behaviour callbacks.

2023-06-26 00:46 UTC, bernardd commented
I initially had exactly the same problem and exactly the same thought regarding the cause. I even tried removing the behaviour and associated callback specs, to no avail. However with a clean checkout/rebuild it eventually worked correctly. My only theory is that for some reason to do with the combination of macros and behaviours and typespecs and all the other magic in use, changing the macro does not always cause the typespec to be correctly regenerated by a normal compile. If you pull the latest version of this branch, and run `MIX_ENV=test mix dialyzer` you should see it correctly generate a warning for the test function in `LetMe.TypespecTestPolicy`.

2023-06-26 12:30 UTC, woylie commented on lib/let_me/builder.ex
> +      @spec authorize!(action, any, any, keyword) :: :ok
```suggestion
      @spec authorize!(action(), any, any, keyword) :: :ok
```

2023-06-26 12:33 UTC, woylie requested changes
Just for consistency, and the test.

I tried it in the let_me repo, and I see a dialyzer warning now.

2023-06-26 23:44 UTC, bernardd commented
Whoops, thanks for the fixes. That should all be correct now.

2023-06-27 00:38 UTC, woylie approved these changes

2023-06-27 00:38 UTC, merged

2023-06-27 00:39 UTC, woylie commented
Thanks!